version: '3'

services:

  proxy:
    build: .
    ports:
      - '3000:3000'

  # booking:
  #   image: airfec/nick_booking
  #   depends_on:
  #     - 'database'
  #   ports:
  #     - '3001:3001'

  # secondcomponent:
  #   image: airfec/booking
  #   ports:
  #     - '3002:3002'

  # thirdcomponent:
  #   image: airfec/booking
  #   ports:
  #     - '3003:3003'

  # fourthcomponent:
  #   image: airfec/booking
  #   ports:
  #     - '3004:3004'

  database:
    image: mongo:latest
    ports:
      - '27017:27017'